kind: pipeline
type: docker
name: default

steps:
  - name: backend
    image: node
    commands:
      - yarn --cwd server install --frozen-lockfile
      - yarn --cwd server build

  - name: frontend
    image: node
    commands:
      - yarn --cwd web install --frozen-lockfile
      - yarn --cwd web build
