version: "3"
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: development
      POSTGRES_DB: development
      POSTGRES_PASSWORD: development
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  backend:
    ports:
      - "3000:4000"
    build: .
    environment:
      NODE_ENV: PRODUCTION
    volumes:
      - "./server/.env:/app/server/.env"
volumes:
  pgdata:
