version: "3"
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: gorm
      POSTGRES_DB: gorm
      POSTGRES_PASSWORD: md5d4b8eb8ecefe02fddb2654d05b502492
    ports: 
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  nginx-react:
    depends_on:
      go:
        condition: service_started
    build:
      context: ../web
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - "./conf/nginx.conf:/etc/nginx/conf.d/default.conf"
  go:
    depends_on:
      db:
        condition: service_started
    build:
      context: ../server
      dockerfile: Dockerfile
    environment: 
      APP_ENV: PRODUCTION
    volumes:
      - "../server/.env:/go/src/project/.env"
volumes: 
  pgdata: