version: "3"
services:
  nginx-react:
    build:
      context: ../web
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - "./conf/nginx.conf:/etc/nginx/conf.d/default.conf"
  go:
    build:
      context: ../server
      dockerfile: Dockerfile
    volumes:
      - "../server/.env:/go/src/project/.env"
