version: "3"
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: sshca
      POSTGRES_DB: sshca
      POSTGRES_PASSWORD: md5a490a675897fb83b0fade1e4a0810d39 #development
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  backend:
    ports: "4000:4000"
    build:
      context: ../server
      dockerfile: Dockerfile
    environment:
      NODE_ENV: PRODUCTION
    volumes:
      - "../server/.env:/src/app/.env"
volumes:
  pgdata:
