version: "3"
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: sshca
      POSTGRES_DB: sshca
      POSTGRES_PASSWORD: md5d4b8eb8ecefe02fddb2654d05b502492
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  backend:
    depends_on:
      db:
        condition: service_started
    build:
      context: ../server
      dockerfile: Dockerfile
    environment:
      APP_ENV: PRODUCTION
    volumes:
      - "../server/.env:/go/src/project/.env"
volumes:
  pgdata:
