name: Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  lintweb:
    name: "Lint Web"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: yarn
      - name: Run ESLint
        uses: sibiraj-s/action-eslint@v1
        with:
          eslintArgs: "--ignore-path=.gitignore --quiet"
          extensions: "ts,tsx"
          annotations: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  styleweb:
    name: "Style Web"
    needs: lintweb
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Prettify code
        uses: creyD/prettier_action@v3.3
        with:
          prettier_options: --write ./web/**.{tsx}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  web:
    name: "Build Web"
    needs: styleweb
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: docker build web
  serverlint:
    name: "Lint Server"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          working-directory: server
  server:
    name: "Build Server"
    needs: serverlint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: docker build server
  clientlint:
    name: "Lint Client"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          working-directory: client
  client:
    name: "Build Client"
    needs: clientlint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Build
        run: |
          cd client
          go build -v .
