name: Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  web:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: docker build web
  server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: docker build server
  client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Build
        run: |
          cd client
          go build -v .
