name: Build

on:
  push:
  pull_request:

jobs:
  lintweb:
    name: "Lint Web"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./web
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        name: Cache Node Modules
        with:
          path: "web/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('web/yarn.lock') }}
      - name: Install modules
        run: yarn --frozen-lockfile
      - name: Run ESLint
        run: yarn run eslint . --ext .ts,.tsx
      - name: Prettify code
        uses: creyD/prettier_action@v3.3
        with:
          prettier_options: -c ./web/src/**
          dry: true
  web:
    name: "Build Web"
    needs: lintweb
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./web
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        name: Cache Node Modules
        with:
          path: |
            "web/node_modules"
          key: ${{ runner.os }}-modules-v1-${{ hashFiles('web/yarn.lock') }}
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Build Web
        env:
          NODE_ENV: production
        run: yarn build
  serverlint:
    name: "Lint Server"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server
    steps:
      - uses: actions/checkout@v2
      - name: Prettify code
        uses: creyD/prettier_action@v3.3
        with:
          prettier_options: -c ./server/src/**
          dry: true
  server:
    name: "Build Server"
    needs: serverlint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        name: Cache Node Modules
        with:
          path: |
            "server/node_modules"
          key: ${{ runner.os }}-modules-v1-${{ hashFiles('server/yarn.lock') }}
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Build Server
        env:
          NODE_ENV: production
        run: yarn build
  clientlint:
    name: "Lint Client"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          working-directory: sshca-client
  client:
    name: "Build Client"
    needs: clientlint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Build
        run: go build -v .
        working-directory: ./sshca-client
      - uses: actions/upload-artifact@v2
        with:
          name: client
          path: ./sshca-client/sshca-client
  tests:
    runs-on: ubuntu-latest
    strategy:
      # when one test fails, DO NOT cancel the other
      # containers, because this will kill Cypress processes
      # leaving the Dashboard hanging ...
      # https://github.com/cypress-io/github-action/issues/48
      fail-fast: false
      matrix:
        # run 3 copies of the current job in parallel
        containers: [1, 2, 3, 4]
    defaults:
      run:
        working-directory: ./server
    needs:
      - server
      - web
    name: "Run Tests With Cypress"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/cache@v2
        name: Cache Node Modules
        with:
          path: |
            "web/node_modules"
            "~/.cache/Cypress"
          key: ${{ runner.os }}-modules-v1-${{ hashFiles('web/yarn.lock') }}
      - uses: actions/cache@v2
        name: Cache Server Node Modules
        with:
          path: "server/node_modules"
          key: ${{ runner.os }}-modules-v1-${{ hashFiles('server/yarn.lock') }}
      - name: Install Dependencies
        run: |
          yarn --cwd ../web --frozen-lockfile
          yarn --cwd ../server --frozen-lockfile
      - name: Build Server
        env:
          DATABASE_URL: file:./dev.db
          NODE_ENV: development
        run: |
          yarn run prisma migrate deploy
          yarn build
      - name: Start Server
        env:
          DATABASE_URL: file:./dev.db
          DOMAIN: localhost
          JWT_PRIVATE: |
            -----BEGIN RSA PRIVATE KEY-----
            MIICXAIBAAKBgQCvpnrazDsPg816ILJsUwOAsR/YDvBOhIHaTGwKxME29wnGKv+D
            IDfQpmFJZjK/v2jCWbr6/ZpyPGbKn8EZ6FjABnVNeUWjECAcDyzzhwRXOd6SQvKL
            GenMzEskQE0EA+hG31kmJrp/Qawf1QDR1ksdxSTX4xugSM0cwzzeC+3LxwIDAQAB
            AoGADhph1tt7Cn3cq6ega84mg9i049YfOU6uVma4bgzqLo2bPUwKg+68TIZvXUNV
            Y8vsj15BAxIFqpJq9m3pRTlAlthgbEcVwQKccTQNkPbE1cxrneQeO7KuRHfjcP4b
            NfoZmog5CtOWiep8bbqp1vU/of4c0E4mPG8RSeTr4qG+PfECQQDVIPAugEBRSZIe
            2wEjA3B0hUdHOM4E1KtpWGJsYEasrrLLEy89R8BUuUWM/8GWjlzdiIIwi4NN3dT3
            rBmrhurrAkEA0vuX/R97cTfZaO+4YfhPsrIEQhGDb3orsWCqNKHpKO4KsrNgpdrI
            /rzv7SVHK9vtSVv/ifZAVaIS2l20ob7zlQJBAI73S2ZGDd75VRVxn2+XTQY8qTWz
            ey9uYZWG/m7onkAT6EelFNksmm264lbU8U1HLjBE8+AQlgHTvpptTcLr/AUCQE9y
            Gctg3XTGmQFgs0eA31HkoqHWQm3pzSYfxjfHeCrHaBPeY9hQSDtUHexoiyJC0Fk9
            YT4sEhGs0/iSLIBzjPkCQFeqMJi2JjsUxtZwWi4utHVDr/7UbIeLQlN5HqPdK4KM
            v2baez1xCVMzSIYjgcEjtTzkQtKZ8nJZpRHGCWTiWdw=
            -----END RSA PRIVATE KEY-----
          JWT_PUBLIC: |
            -----BEGIN PUBLIC KEY-----
            MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCvpnrazDsPg816ILJsUwOAsR/Y
            DvBOhIHaTGwKxME29wnGKv+DIDfQpmFJZjK/v2jCWbr6/ZpyPGbKn8EZ6FjABnVN
            eUWjECAcDyzzhwRXOd6SQvKLGenMzEskQE0EA+hG31kmJrp/Qawf1QDR1ksdxSTX
            4xugSM0cwzzeC+3LxwIDAQAB
            -----END PUBLIC KEY-----
        run: yarn start &
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          record: true
          parallel: true
          group: "Github Actions"
          install: false
          start: yarn start
          working-directory: web
          wait-on: "http://localhost:3000, http://localhost:3000/api/graphql"
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          # Recommended: pass the GitHub token lets this action correctly
          # determine the unique run id necessary to re-run the checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: cypress-screenshots
          path: ./web/cypress/screenshots
      # Test run video was always captured, so this action uses "always()" condition
      - uses: actions/upload-artifact@v1
        if: always()
        with:
          name: cypress-videos
          path: ./web/cypress/videos
